# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170129_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='long',
            field=models.IntegerField(default=0),
        ),
    ]
